/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'followersCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'totalLikes' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'postsCount' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const SocialFeature = IDL.Record({
  'name' : IDL.Text,
  'engagementRate' : IDL.Nat,
  'iconUrl' : IDL.Text,
  'postsCount' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'mediaBlob' : ExternalBlob,
  'caption' : IDL.Text,
  'mediaType' : MediaType,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'authorPrincipal' : IDL.Principal,
});
export const Hashtag = IDL.Record({
  'postCount' : IDL.Nat,
  'postIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
});
export const UserWithTrendingPosts = IDL.Record({
  'username' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'trendingPostsCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [ExternalBlob, MediaType, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createVisualEffect' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getEngagementRate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'getFeatureDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SocialFeature)],
      ['query'],
    ),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostsByUser' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getRelatedFeatures' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(SocialFeature))],
      ['query'],
    ),
  'getTopHashtags' : IDL.Func([], [IDL.Vec(Hashtag)], ['query']),
  'getTopTrendingUsers' : IDL.Func(
      [],
      [IDL.Vec(UserWithTrendingPosts)],
      ['query'],
    ),
  'getTrendingFeatures' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(SocialFeature))],
      ['query'],
    ),
  'getTrendingPosts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'likesCount' : IDL.Nat, 'postId' : IDL.Nat }))],
      ['query'],
    ),
  'getTrendingPostsList' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isViral' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPosts' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'searchUsers' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'followersCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'totalLikes' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'postsCount' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const SocialFeature = IDL.Record({
    'name' : IDL.Text,
    'engagementRate' : IDL.Nat,
    'iconUrl' : IDL.Text,
    'postsCount' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'mediaBlob' : ExternalBlob,
    'caption' : IDL.Text,
    'mediaType' : MediaType,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'authorPrincipal' : IDL.Principal,
  });
  const Hashtag = IDL.Record({
    'postCount' : IDL.Nat,
    'postIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
  });
  const UserWithTrendingPosts = IDL.Record({
    'username' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'trendingPostsCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [ExternalBlob, MediaType, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createVisualEffect' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getEngagementRate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'getFeatureDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SocialFeature)],
        ['query'],
      ),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostsByUser' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getRelatedFeatures' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(SocialFeature))],
        ['query'],
      ),
    'getTopHashtags' : IDL.Func([], [IDL.Vec(Hashtag)], ['query']),
    'getTopTrendingUsers' : IDL.Func(
        [],
        [IDL.Vec(UserWithTrendingPosts)],
        ['query'],
      ),
    'getTrendingFeatures' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(SocialFeature))],
        ['query'],
      ),
    'getTrendingPosts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'likesCount' : IDL.Nat, 'postId' : IDL.Nat }))],
        ['query'],
      ),
    'getTrendingPostsList' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isViral' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPosts' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };