/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'authorPrincipal' : Principal,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Hashtag {
  'postCount' : bigint,
  'postIds' : Array<bigint>,
  'name' : string,
}
export type MediaType = { 'video' : null } |
  { 'photo' : null };
export interface Post {
  'id' : bigint,
  'createdAt' : bigint,
  'mediaBlob' : ExternalBlob,
  'caption' : string,
  'mediaType' : MediaType,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'authorPrincipal' : Principal,
}
export interface SocialFeature {
  'name' : string,
  'engagementRate' : bigint,
  'iconUrl' : string,
  'postsCount' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'username' : string,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'totalLikes' : bigint,
  'followingCount' : bigint,
  'profilePicture' : [] | [ExternalBlob],
  'postsCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithTrendingPosts {
  'username' : string,
  'profilePicture' : [] | [ExternalBlob],
  'trendingPostsCount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a comment to a post. Requires #user role.
   */
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new post. Requires #user role.
   */
  'createPost' : ActorMethod<
    [ExternalBlob, MediaType, string, Array<string>],
    bigint
  >,
  /**
   * / Create a visual effect. Requires #user role.
   */
  'createVisualEffect' : ActorMethod<
    [string, string, bigint, string],
    undefined
  >,
  /**
   * / Delete a comment. Requires #user role. Only comment author or post owner can delete.
   */
  'deleteComment' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete a post. Requires #user role and caller must be the post owner.
   */
  'deletePost' : ActorMethod<[bigint], undefined>,
  /**
   * / Follow a user. Requires #user role.
   */
  'followUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Get the calling user's own profile. Requires #user role.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get paginated comments for a post. No auth required.
   */
  'getComments' : ActorMethod<[bigint, bigint, bigint], Array<Comment>>,
  /**
   * / Get engagement rate for content. No auth required.
   */
  'getEngagementRate' : ActorMethod<[string, string], number>,
  /**
   * / Get feature details. No auth required.
   */
  'getFeatureDetails' : ActorMethod<[string], [] | [SocialFeature]>,
  /**
   * / Get paginated feed ordered by recency. No auth required.
   */
  'getFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  /**
   * / Get paginated followers of a user. No auth required.
   */
  'getFollowers' : ActorMethod<[Principal, bigint, bigint], Array<Principal>>,
  /**
   * / Get paginated following of a user. No auth required.
   */
  'getFollowing' : ActorMethod<[Principal, bigint, bigint], Array<Principal>>,
  /**
   * / Get a post by id. No auth required (public content).
   */
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  /**
   * / Get paginated posts by a specific user. No auth required.
   */
  'getPostsByUser' : ActorMethod<[Principal, bigint, bigint], Array<Post>>,
  /**
   * / Get related features. No auth required.
   */
  'getRelatedFeatures' : ActorMethod<[string], [] | [Array<SocialFeature>]>,
  /**
   * / Get top hashtags. No auth required.
   */
  'getTopHashtags' : ActorMethod<[], Array<Hashtag>>,
  /**
   * / Get users who created most trending posts. No auth required.
   */
  'getTopTrendingUsers' : ActorMethod<[], Array<UserWithTrendingPosts>>,
  /**
   * / Get trending features. No auth required.
   */
  'getTrendingFeatures' : ActorMethod<[], [] | [Array<SocialFeature>]>,
  /**
   * / Get trending posts summary. No auth required.
   */
  'getTrendingPosts' : ActorMethod<
    [],
    Array<{ 'likesCount' : bigint, 'postId' : bigint }>
  >,
  /**
   * / Get posts ordered by likesCount descending. No auth required.
   */
  'getTrendingPostsList' : ActorMethod<[bigint, bigint], Array<Post>>,
  /**
   * / Get any user's profile by principal. Caller must be #user or admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check if the calling user is following a target. Requires #user role.
   */
  'isFollowing' : ActorMethod<[Principal], boolean>,
  /**
   * / Check if the calling user has liked a post. Requires #user role.
   */
  'isLiked' : ActorMethod<[bigint], boolean>,
  /**
   * / Check if content is viral. No auth required.
   */
  'isViral' : ActorMethod<[string, string], boolean>,
  /**
   * / Like a post. Requires #user role.
   */
  'likePost' : ActorMethod<[bigint], undefined>,
  /**
   * / Register a new user profile. Requires #user role (authenticated principal).
   */
  'registerUser' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  /**
   * / Save/update the calling user's own profile. Requires #user role.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search posts by caption. No auth required.
   */
  'searchPosts' : ActorMethod<[string, bigint, bigint], Array<Post>>,
  /**
   * / Search users by username. No auth required.
   */
  'searchUsers' : ActorMethod<[string, bigint, bigint], Array<UserProfile>>,
  /**
   * / Unfollow a user. Requires #user role.
   */
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Unlike a post. Requires #user role.
   */
  'unlikePost' : ActorMethod<[bigint], undefined>,
  /**
   * / Update own profile. Requires #user role and caller must own the profile.
   */
  'updateProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];